### ISSUE TITLE
Warning for missing methods defined by prototypes.

### ISSUE THREAD

**Issue by Darkyenus** [Darkyenus/glsl4idea#1]

**Comment by AbigailBuccaneer** [comment]
I'm not entirely sure this is appropriate - it's possible to create two shader objects for the same shader stage, with source like so:

```GLSL
void f() { /* ... */}
```

```GLSL
void f();
void main() { f(); }
```

...and then compile them, attach them both to the same program object, and then link it. It's not recommended as something you should do, and so some indication that a declared function isn't defined would be nice. I think it should just use a different gutter icon than the implemented method icon if it's not implemented.

**Comment by Darkyenus** [comment]
It could be implemented as a warning which can be turned off or suppressed by a comment, which would bring both advantages.

**Comment by Darkyenus** [comment]
I will accept PR for this if somebody finds it useful enough to implement it, but otherwise it is not worth having. I suspect that most people that forward-declare functions also put them in different files anyways and the inspection would be contraproductive most of the time.
