### ISSUE TITLE
Switch statement expects boolean expression

### ISSUE THREAD

**Issue by TomislavUzelac** [Darkyenus/glsl4idea#100]
I'm using version 1.9 with PyCharm 4.5.3. and the switch statement is not recognized.

The following is marked as error, right after closing parentheses on the first line (also after each "case"). The error is "Missing ';' after expression".

    switch (_texture_unit) {
        case 0: gl_FragColor = process(atlas0, uv); break;
        case 1: gl_FragColor = process(atlas1, uv); break;
        case 2: gl_FragColor = process(atlas2, uv);
    }

**Comment by Darkyenus** [comment]
This has been already fixed, but not yet released. We should do a release soon. Thanks for reporting though!

**Comment by TomislavUzelac** [comment]
Thanks for the updates.

I've upgraded to 1.10, but now it reports "Condition must be a boolean expression".

"_texture_unit" is highlighted in red, as error.

**Comment by Darkyenus** [comment]
Fixed in ce961524c44d7223796101d7e457cb01e8ec6ba0 with some extra checks for switches.
