### ISSUE TITLE
Acknowledge preprocessor statements

### ISSUE THREAD

**Issue by Darkyenus** [Darkyenus/glsl4idea#11]

**Comment by AbigailBuccaneer** [comment]
I've started work on this on my fork. Unfortunately I can't assign this issue to myself.

**Comment by Darkyenus** [comment]
Can I directly contact you somehow? (Or you can contact me if you don't want to reveal your mail, I have my mail public on my profile)

**Comment by AbigailBuccaneer** [comment]
Sure thing; I'll email you now.
