### ISSUE TITLE
Refactor file name message

### ISSUE THREAD

**Issue by Jose-Parente** [Darkyenus/glsl4idea#115]
This issue was first raised on Android Studio:
https://code.google.com/p/android/issues/detail?id=198157

To reproduce, create a new .vert/.frag file, right click on it, and try refactor > rename...
The rename message says: "Rename file FILE and its usages to:"

Traced the problem to the implementation of
GLSLFindUsagesProvider.java@getDescriptiveName()

Tested on:
IntelliJ IDEA 15.0.2
Build #IC-143.1184, built on December 7, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

and 
Android Studio 2.0 Preview 4
Build #AI-143.2489090, built on December 15, 2015
JRE: 1.8.0_65-b17 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by Darkyenus** [comment]
Thanks for good report, fixed in 002ca38f06ed45afffcc1161bb4a93e81b1d627e, will be included in next release.
