### ISSUE TITLE
Parse error causes Intellij to crash

### ISSUE THREAD

**Issue by Jyro117** [Darkyenus/glsl4idea#121]
While I understand that parse errors can cause issues I wasn't expecting the following code snippet to cause a ton of issues:
`
#version 120

const int SIZE = _SIZE_;

const int sampleSize = SIZE * * ;

void main() {
	gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
`
I was in the middle of changing the names of a few variables in my files when I encountered the IDE reporting: "Unable to save settings: Failed to save settings. Please restart IntelliJ IDEA" Shortly followed by a complete freeze of the IDE. I believe it has something to do with the "SIZE * * ;" causing an issue. Even clearing the file externally so it had nothing in it did not prevent the IDE from freezing shortly after load. I had to create a new file with the same name in order to be able to open any file with the same path that caused the crash.

**Comment by Darkyenus** [comment]
Thanks for report, this one was a bit tricky due to one small error cascading into series of obscure problems, but it is resolved at last. Fixed in 56a087ad9dbb4e63013ea6b9d699607e01f844fe, publishing new version now.
