### ISSUE TITLE
support .vsh and .fsh file types

### ISSUE THREAD

**Issue by egoroof** [Darkyenus/glsl4idea#122]
Add support for .vsh (same as .vert) and .fsh (same as .frag) file extensions.
PR https://github.com/Darkyenus/glsl4idea/pull/123

**Comment by egoroof** [comment]
Could you please publish it to jetbrains plugin registry? - so I'll be able to use it

**Comment by Darkyenus** [comment]
I'll do a release when enough changes accumulate (or a critical bug is fixed), I don't want to release too often as it gets annoying.

However, you can already reassign those extensions to be GLSL files, even without this change:
Preferences -> Editor -> File Types and add those (or any other extensions) to the list for OpenGL Shading Language.

What that PR really did was just changing the default bindings, what is really used is left to the user.

**Comment by egoroof** [comment]
Yeah, it works! Thanks a lot!
