### ISSUE TITLE
Enable syntax highlight

### ISSUE THREAD

**Issue by nuthinking** [Darkyenus/glsl4idea#125]
After installing the plugin ([GL Support](https://plugins.jetbrains.com/plugin/6993-glsl-support)) I still don't get syntax highlighting. When I create a new .glsl file I get this:
![screen shot 2017-07-12 at 12 24 25](https://user-images.githubusercontent.com/163635/28113563-56f8f84c-66fd-11e7-9648-f7870d8ad869.png)

No option to associate to the extension to the plugin.

I got these new templates:
![screen shot 2017-07-12 at 12 24 03](https://user-images.githubusercontent.com/163635/28113666-b9cc1a30-66fd-11e7-9625-6150d59699f7.png)

But there is no way to instantiate them since they don't appear in the menu: 
![screen shot 2017-07-12 at 12 27 54](https://user-images.githubusercontent.com/163635/28113627-901b2140-66fd-11e7-8c18-ad7b9db3ffd5.png)

I am running WebStorm 11.03. Any idea what is going on?

Thanks!

**Comment by Darkyenus** [comment]
Could you please attach your "idea.log"? (probably called differently in WebStorm) I suspect that it crashes at some point during initialization and that should get recorded in logs.

Logs should be accessible through `Help->Show log`, or in similar way.
