### ISSUE TITLE
Include directive support

### ISSUE THREAD

**Issue by dylanede** [Darkyenus/glsl4idea#130]
I see that #52 added support for lexing include directives. It would be nice if headers could then be parsed and taken into account for analysis.

**Comment by Darkyenus** [comment]
The analysis is not very good right now, so it wouldn't be of much use. But it should be relatively easy to add after that.

**Comment by tlf30** [comment]
If nothing else, it would be nice if syntax highlighting worked on include directives.

**Comment by Darkyenus** [comment]
Implemented by f738c35
