### ISSUE TITLE
Support for code fragments

### ISSUE THREAD

**Issue by OndrejSpanel** [Darkyenus/glsl4idea#138]
Sometimes the application is creating complete shaders from individual string fragments. While it is possible to get syntax highlighting by using code injection comments, the code is highlighted as containing many errors, because its syntax does not comply with the complete HLSL shader. 

Example code (in Scala) could look like:

```
val prefix = "void main() {"

val suffix = "}"

//language=GLSL
val inside = """
vec4 color = vec4(0);
gl_FragColor = color;
"""

val shader = prefix + inside + suffix
```

Such code causes an error "Expression is not allowed here". While this is understandable, it would be very handy if one could somehow get GLSL highlighting even for such partial shader fragments. Perhaps a different language name (GLSL_part?) could be used to indicate the string is not a complete shader?

![image](https://user-images.githubusercontent.com/6927223/45599255-86356e80-b9e8-11e8-85ca-0165ea3df98c.png)

**Comment by edwinRNDR** [comment]
I have only recently learned about language injection, and now I have the exact same use case (albeit in Kotlin) as the OP.

Are there plans for implementing this?

**Comment by edwinRNDR** [comment]
@Darkyenus do you have any tips or tricks in case I, or someone else, would like to pick this up?

**Comment by Darkyenus** [comment]
This is not a high priority issue, because it would not be impossible to do pretty much anything else besides token highlighting.

I suggest using full shader files with preprocessor conditions instead, the plugin manages to handle these a bit better (and they are usually a bit less error prone, in my experience. Plus you can implement hot-reloading easily for them.)

**Comment by edwinRNDR** [comment]
I think token highlighting, and especially those of parens are a definite improvement over not having those.

Unfortunately the suggested preprocessor conditions don't fit my workflow as shaders are generated by a more or less pluggable system.

**Comment by singalen** [comment]
I'm reading the language injection doc, and it has a "prefix" and "suffix" feature: https://www.jetbrains.com/help/clion/using-language-injections.html#use-language-injection-comments
Doesn't it completely cover this request?

**Comment by edwinRNDR** [comment]
@singalen I was completely unaware of those features. And yes, they do cover everything when `prefix` and `suffix` are used to wrap everything inside a function. Thank you so much for pointing that out!

**Comment by OndrejSpanel** [comment]
prefix / suffix looks nice, but I cannot find the exact syntax I should use, they seem to be ignored for me

I have tried:

```scala
  // language=GLSL prefix=void main() { suffix=}
```

```scala
  // language=GLSL prefix="void main() {" suffix="}"
```

**Comment by Darkyenus** [comment]
This works for me in Java:
```java
// langauge=GLSL
@Language(value="GLSL", prefix="void _() {", suffix="}")
String code = """
        vec4 color = vec4(0.0);
        gl_FragColor = color;
        """;
```
Kotlin will probably have something similar (possibly with intellij-annotations).

Since there is no clear good way to solve this directly in plugin and this is good enough, I'm closing this.
