### ISSUE TITLE
Function macro support

### ISSUE THREAD

**Issue by devlato** [Darkyenus/glsl4idea#144]
Hey,

we have a `saturate` macro defined in the code. But IDE complains about the macro (see attachments), seems like it doesn't recognize it at all. Does the plugin provide IDE with macro support?

<img width="473" alt="Screen Shot 2019-04-02 at 10 47 24" src="https://user-images.githubusercontent.com/1210210/55366608-30b05180-5535-11e9-97f6-1c6bddc70635.png">
<img width="434" alt="Screen Shot 2019-04-02 at 10 47 33" src="https://user-images.githubusercontent.com/1210210/55366609-30b05180-5535-11e9-95ca-a8fb751e1c79.png">

**IDE**: Webstorm 2018.3.5 build #WS-183.5912.23 from Feb 27, 2019
**OS**: macOS Mojave 10.14.3
**Plugin version**: 1.17

**Comment by devlato** [comment]
A small update: the issue reproduces with the latest Webstorm (2019.1 build #WS191.6183.63 from March 21, 2019) and the latest plugin version (1.18).

**Comment by Darkyenus** [comment]
Function macros are unfortunately not supported yet.

**Comment by NickCody** [comment]
+1

**Comment by cielsys** [comment]
+1 for macro functions, please.
This plugin is so helpful! Thank you!
