### ISSUE TITLE
Incorrect "Missing return statement" error because switch statement that always returns was not recognized

### ISSUE THREAD

**Issue by mjwach** [Darkyenus/glsl4idea#149]
This kind of method gives me an annoying "Missing return statement" error in the IDE, even though the method makes sense and compiles correctly:

    int testo(int i)
    {
    	switch (i)
    	{
    		case 0: return 7;
    		default: return 33;
    	}
    }

**Comment by Darkyenus** [comment]
Thanks for the report!
