### ISSUE TITLE
Syntax highlighting for operators

### ISSUE THREAD

**Issue by Zoodinger** [Darkyenus/glsl4idea#151]
GLSL plugin could easily support highlighting for additional operators.

I proposed a solution here a while ago: https://github.com/Darkyenus/glsl4idea/pull/150 but thought I should create an issue for it to make the request official.

It's a very small change that doesn't conflict with existing code.

**Comment by Darkyenus** [comment]
No need to create issues, the PR is enough and preferred. I just currently don't have time to work on this plugin.
