### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by Timxu2016** [Darkyenus/glsl4idea#153]
Hi guys, I' m using Android Studio3.6.3 and just install glsl plugin 1.19.

I can see the plugin installed in the setting, but nothing happena when i edit an glsl file, no syntax highlighting/Grammar checking,just nothing.

I've tried reinstall the plugin but still doesn't work.

Please help ,great thanks!

**Comment by Timxu2016** [comment]
![11](https://user-images.githubusercontent.com/19217893/81927912-045f7380-9617-11ea-93db-adc74ec030fb.PNG)

**Comment by Darkyenus** [comment]
You may have a wrong file asociation. Go to preferences -> Editor -> File Types -> OpenGL Shading Language and ensure that you have the file extension associated correctly. (You may also need to delete previous association to plain text files.)

It will look something like this:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/5280068/81937815-635fc100-95f4-11ea-80da-801b317ecdce.png">

**Comment by Timxu2016** [comment]
> You may have a wrong file asociation. Go to preferences -> Editor -> File Types -> OpenGL Shading Language and ensure that you have the file extension associated correctly. (You may also need to delete previous association to plain text files.)
> 
> It will look something like this:
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/5280068/81937815-635fc100-95f4-11ea-80da-801b317ecdce.png">
> 
> You can also check the [official documentation](https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html#) for the File Type page.
> 
> I am closing this issue as it is probably not a plugin issue, but feel free to keep commenting. I will reopen it if it turns out that this is indeed a bug.

Problem solved, great thanks!
