### ISSUE TITLE
Support for including glsl file as C++ R string literal

### ISSUE THREAD

**Issue by jaw** [Darkyenus/glsl4idea#156]
Since C++ 11 it's possible to include a text file directly into a C++ multi line string literal like so:

## C++:
```cpp
constexpr const char shader_source[] =
  #include "shaders/shader.glsl"
;
```

## shader.glsl:
```
R"str_end(
#version 430
... many lines of code without \n or " around them ...
)str_end"
```

### Notes
- "str_end" can be any string as long as it's the same in the beginning.
- the text file has to contain these R constructs as the preprocessor can not react to something within a string 

## What happens now?
The GLSL plugin marks the first and last lines as an error.
Otherwise it syntax highlights the file correctly.

## What do I want?
Not to have the error validator consider these as part of the code if present.

Should be easy to implement and help me a LOT!
Thanks.

**Comment by Darkyenus** [comment]
This is technically a CLion issue - `str_end` is not a real part of the string, it is just a string syntax.

Please see [CPP-12647](https://youtrack.jetbrains.com/issue/CPP-12647) instead.
