### ISSUE TITLE
Redundant new line on lambda expression wrap in Kotlin

### ISSUE THREAD

**Issue by vagran** [Darkyenus/glsl4idea#157]
This plugin somehow affects editing Kotlin files. The issue exists only when the plugin is enabled.
Type in some Kotlin file some expression with lambda last argument, e.g.
```kotlin
synchronized(a) {

}
```
When `{` is typed, `}` is auto inserted, the cursor is between braces:
![image2](https://user-images.githubusercontent.com/6065976/103222189-b04a9a80-492c-11eb-9f54-d8b43b6a58b0.png)
Then pressing enter inserts two new lines instead of one:
![image](https://user-images.githubusercontent.com/6065976/103222260-c0627a00-492c-11eb-8c27-6492cc25e985.png)

Plugin version 1.19
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020

**Comment by Darkyenus** [comment]
That's odd. I'll see if I can reproduce as soon as I have some free time.

**Comment by lgorence** [comment]
I am also facing this issue. There is a bug on the Kotlin plugin's issue tracker that references this same behavior.
https://youtrack.jetbrains.com/issue/KTIJ-631

**Comment by Darkyenus** [comment]
I suspect this may be fixed by 1.20 which will be released today. Please reopen if this is not the case.
