### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by grisevg** [Darkyenus/glsl4idea#17]
I'm not savy with building plugin jar, could you please provide some basic instructions?
Thanks

**Comment by Darkyenus** [comment]
I have added some info and already compiled .jar to releases, which should be enough to get going, feel free to ask if you have any questions.

**Comment by grisevg** [comment]
Thank you very much!

**Comment by Gustl22** [comment]
@Darkyenus I was able to build the plugin. But if I install the jar, the test files aren't recognized. What could be the issue?

**Comment by Darkyenus** [comment]
@Gustl22 Two things come to mind: make sure that you don't have two GLSL plugins installed at the same time, and check the file associations in Settings -> File Types -> OpenGL Shading Language.

**Comment by Gustl22** [comment]
Ok, I finally got it running:
Needed to set the [compile version](https://stackoverflow.com/questions/25115059/intellij-compile-for-java-7-jre-using-java-8-sdk) to 8.

**Comment by Darkyenus** [comment]
You shouldn't have to, I compile with Java 7. And I am not sure what would need to happen to compile but not work... maybe only if it was compiled with higher version than what the IntelliJ's java supports (IIRC its 8?).
