### ISSUE TITLE
CLion hangs when editing glsl file

### ISSUE THREAD

**Issue by andmoos** [Darkyenus/glsl4idea#174]
**Describe the bug**
CLion hangs when editing a simple glsl file and after a kill -9 and reopen no changes are persisted.

**To Reproduce**
```glsl
#version 460

void main() {
    for (uint i = 0; i < 2; ++i)
    {
        // change the "2" in the above "i < 2" a couple of times to other values like 3, 4, 5.... to crash CLion
    }
}
```

**Versions**
 - IDE: CLion CL-222.4345.21
 - Plugin: 1.22

**Additional context**
For me the issue arises even in an empty project with just a single glsl file with the above content.

**Comment by Darkyenus** [comment]
Thanks for the report!
