### ISSUE TITLE
crash on start (plugin version 1.2)

### ISSUE THREAD

**Issue by brempusz** [Darkyenus/glsl4idea#21]
OSX Yosemite 10.10.2
IntelliJ IDEA 14.1
Build #IU-141.177, built on March 23, 2015
JRE: 1.6.0_65-b14-466.1-11M4716 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple Inc.

```
Plugin 'GLSL' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: glslplugin/components/GLSLTemplatesLoader : Unsupported major.minor version 51.0 [Plugin: GLSL]
   ...
```

51.0 is java 1.7; it can't be run on 1.6, JDK 1.6 is required on OSX - It is possible to run IDEA on jdk 7/8 but with issues. Please provide version compiled for 1.6.

**Comment by Monkeymoomoo** [comment]
I have the same issue.

**Comment by Darkyenus** [comment]
There actually is an experimental build of IntelliJ for OSX that uses Java 8, but I'll try to recompile for Java 6 anyway.

**Comment by Darkyenus** [comment]
Added Java 6 version to downloads https://github.com/Darkyenus/glsl4idea/releases/download/1.2/GLSLPluginJava6.jar

**Comment by brempusz** [comment]
Thanks!
