### ISSUE TITLE
Not working on CLion

### ISSUE THREAD

**Issue by theplatapi** [Darkyenus/glsl4idea#22]
I've tried installing both of the precompiled versions of this plugin, but the GLSL files I have remain unhighlighted. The older version of this plugin on the Jetbrains repository does activate properly, but it's impossible to configure it so it looks good with the Darkula theme.

I'm running on CLion 1.0

**Comment by Darkyenus** [comment]
Please check the logs, I suspect that the api in CLion has changed slightly and the plugin crashes, related to #23.

**Comment by Darkyenus** [comment]
Try the latest version https://github.com/Darkyenus/glsl4idea/releases/tag/1.3

**Comment by theplatapi** [comment]
The latest one works great! Thank you.
