### ISSUE TITLE
Empty #defines are not ignored when checking syntax.

### ISSUE THREAD

**Issue by agatti** [Darkyenus/glsl4idea#36]
As per subject, here's an example that triggers a syntax error:

```glsl
#define DUMMY
attribute DUMMY vec4 vector;
```

yields a "Missing ';' after declaration" at the beginning of ```vec4``` error.

**Comment by AbigailBuccaneer** [comment]
This was fixed by ca5372f49be5afececd8cb20816c4bf65fccc288, which will be in the next release. It currently just accepts all preprocessor tokens until the end of the line (which does mean it accepts some invalid inputs, but it's a start).

**Comment by AbigailBuccaneer** [comment]
Wait, my mistake, I've potentially misunderstood this.

Is the bug that in the current release it doesn't correctly parse the `#define` directive (and so eats a token from the next line) or that it doesn't support preprocessor token replacement? If it's the latter, that's going to be part of a larger task which I mentioned in #32.

**Comment by agatti** [comment]
I assume it's the latter, so I guess it's part of #32 then.  If so, then feel free to close this bug.  All my shaders have a

```glsl
#ifdef GL_ES
#define LOW lowp
#define MED mediump
#define HIGH highp
precision mediump float;
#else
#define LOW
#define MED
#define HIGH
#endif
```

prefix block, so I'll find out soon enough when this will be get fixed :)

**Comment by Darkyenus** [comment]
I think the reported issue was actually same as #46, not #32.
