### ISSUE TITLE
Files with errors should be shown in the project tree

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Darkyenus/glsl4idea#42]
If a Java file contains an error, then that file and its parent packages will have a red error squiggle in the project tree viewer (and on the breadcrumb menu at the top). This isn't the case for GLSL files. I can't find what needs to be implemented to do this.

**Comment by Darkyenus** [comment]
The only plugins I found which do this are big official ones, like Gradle one. It will probably be hard to find out how to do it, since search terms are generic.

Also: Do we need it when most plugins don't do it? I'd argue that this makes it more of an enhancement than bug.

**Comment by AbigailBuccaneer** [comment]
See the `piglit` branch - it adds hundreds of test shaders; and it'd be nice to see which ones pass and which ones don't.

It turns out that it's really simple to do this - once you've waded through reams of code figuring out how to. Did you know `WolfTheProblemSolverImpl#orderVincentToCleanTheCar` is related to this functionality? I do now.

**Comment by Darkyenus** [comment]
Yeah, I figured that this was for poor-man's test automation, but it should do fine for now. Btw. make sure that piglit's licence allows us to put these tests into our repo.
