### ISSUE TITLE
Does custom structureview do anything?

### ISSUE THREAD

**Issue by Darkyenus** [Darkyenus/glsl4idea#49]
Removing `<lang.psiStructureViewFactory language="GLSL" implementationClass="glslplugin.structureview.GLSLStructureViewFactory"/>` from plugin.xml doesn't seem to change anything, and that is the only entry point. What does it actually do then? Do we need it?

**Comment by jepebe** [comment]
If I remember correctly I think it was made to enable the structure view.

**Comment by Darkyenus** [comment]
You are right, I forgot there is that feature since I don't use it. Looks like it works well, but will probably need some minor tweaking.
