### ISSUE TITLE
String literals should be lexed for ARB_shading_language_include

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Darkyenus/glsl4idea#52]
In our engine we use a preprocessor, which allows us to use `#include "filename.glsl"` in shaders. The syntax is the same as the [ARB_shading_language_include](https://www.opengl.org/registry/specs/ARB/shading_language_include.txt) extension.

In order for this extension (and, my real reason to suggest this, our codebase) to be supported in terms of tokens, it's necessary to lex string literals. This should be very easy as they contain no special characters or escaping. Parser support isn't required, as they're only valid in preprocessor directives which already just eat all the tokens until the end of the line.

**Comment by Darkyenus** [comment]
I believe they should be parsed only in preprocessor flex mode, so it still correctly complains about invalid char elsewhere. Just a small note.
