### ISSUE TITLE
Precision markers are not higlighted correctly.

### ISSUE THREAD

**Issue by agatti** [Darkyenus/glsl4idea#53]
In version 1.7 on CLion 1.0.1, the following code snippet:

```glsl
#ifdef GL_ES
precision mediump float;
precision mediump vec2;
precision mediump vec4;
precision mediump sampler2D;
#endif // GL_ES
```

gets improperly highlighted for vec2 and vec4, as per the attached screenshot.
![screen shot 2015-05-05 at 12 11 16](https://cloud.githubusercontent.com/assets/235740/7470773/1cb67d7e-f320-11e4-8c14-fc500a4d142c.png)

I suspect this happens on more types, but I didn't do any further tests.  Adding precision markers to vec2/vec4 types seems to be legal according to section 4.5.2 of the specifications.

**Comment by Darkyenus** [comment]
This does not seem to be connected with types but with (lazy?) highlighting. I'll investigate more.
