### ISSUE TITLE
Geometry shader syntax error

### ISSUE THREAD

**Issue by wyozi** [Darkyenus/glsl4idea#61]
The semicolon errors with "Expected a type specifier."

```glsl
layout(points) in;
layout(line_strip, max_vertices = 6) out;
```

**Comment by AbigailBuccaneer** [comment]
Relevant part from the [GLSL 4.5 spec](https://www.opengl.org/registry/doc/GLSLangSpec.4.50.diff.pdf) §4.4:

> Layout qualifiers can appear in several forms of declaration. They can appear as part of an interface block definition or block member, as shown in the grammar in the previous section. They can also appear with just an interface qualifier (a storage qualifier that is `in`, `out`, or `uniform`) to establish layouts of other declarations made with that interface qualifier:
>     layout-qualifier interface-qualifier ;
> Or, they can appear with an individual variable declared with an interface qualifier:
>    layout-qualifier interface-qualifier declaration ;
