### ISSUE TITLE
Unable to install on IntelliJ 13

### ISSUE THREAD

**Issue by Tosken1337** [Darkyenus/glsl4idea#63]
I am not able to install the Plugin in Intellij 13.
I get the message that the plugin is not compatible with the current version.

**Comment by Darkyenus** [comment]
Current supported version is 14 and backporting may not be trivial if we use some of the newer APIs. You can try messing with plugin.xml to go around version check, but success if not guaranteed (it will probably work, but I didn't test it). If you are successful, PR is welcome.
