### ISSUE TITLE
Preprocessor directives immediately after functions are marked as unreachable

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Darkyenus/glsl4idea#65]
The following warning is invalid:

```C
#ifdef DEFINE_F
int f() { return 3; }
#endif // warning: unreachable expression
```

**Comment by Darkyenus** [comment]
Hmm, yes, this is one of the problems that arise when preprocessor directives are bundled with the token before. Easiest solution would probably be to just not try to mark preprocessor directives. Which is the valid solution as well, thinking about it. I'll probably fix it later today or tomorrow if I have time.
