### ISSUE TITLE
Can't create files with an extension other than .glsl

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Darkyenus/glsl4idea#72]
If I use 'Right click › New › GLSL Shader', and enter 'Shader.vert', it creates a new file called 'Shader.vert.glsl'. It still recognises it as a GLSL file, but I then have to manually rename it to 'Shader.vert'.

**Comment by Darkyenus** [comment]
I think I have figured this one out. I'll take over if you don't mind.
